# Generated by Django 6.0 on 2026-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("cashless", "Перевод на счет")],
                default="cashless",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
