# Generated by Django 6.0 on 2026-01-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_subscription_course_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(default=3000, verbose_name="Цена"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(default=1000, verbose_name="Цена"),
        ),
    ]
